name: 'Run e2e tests'
description: 'Run e2e tests for @progymedia/strapi-studio Community Edition'
inputs:
  jestOptions:
    description: 'Jest options'
  enableFutureFeatures:
    description: 'Enable future unstable features'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/script.sh
      env:
        JEST_OPTIONS: ${{ inputs.jestOptions }}
        STRAPI_FEATURES_FUTURE_RELEASES_SCHEDULING: ${{ inputs.enableFutureFeatures }}
      shell: bash
