name: 'Run API tests'
description: 'Run API tests for @progymedia/strapi-studio'
inputs:
  dbOptions:
    description: 'Database options'
    required: true
  jestOptions:
    description: 'Jest options'
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/script.sh
      env:
        DB_OPTIONS: ${{ inputs.dbOptions }}
        JEST_OPTIONS: ${{ inputs.jestOptions }}
      shell: bash
